from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
import os

chatbot = ChatBot(name ="Radiata_B")
trainer = ListTrainer(chatbot)


#data
#It seems that if I put yaml, json, or text file as data, it does not show very good results. maybe it's because of my lack of skills or misunderstanding of how yaml file works... sorry for the inconvinience
#Furthermore, given that English is not my primary language, it is plausible that the comments or data contained within this file may exhibit grammatical inaccuracies. Sorry for my bad English.

#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#stories
trainer.train(["What is Alan Institute?",
               "Institute that makes charity for ppl with talent",])
trainer.train(["What is LycoReco?",
    "LycoReco is one of branches of DA, but it takes an undercover as cafe.",])
trainer.train(["What is DA?",
    "It is an organization that prevents criminals from even commiting the crime.",])
trainer.train(["What is Lycoris",
    "The only-girls assassins, spies and agents made up of orphans, working for DA. ",])
trainer.train(["Why is it called Lycoris?",
    "DA was originally called 'Higanbana' in pre-meiji era, which means Lycoris Radiata.(Spider Lily)",])
trainer.train(["What is the special skill of Chisato?",
    "She can dodge bullets.",])
trainer.train(["What is the speical skill of Majima?",
               "His hearing skill is on monster level",])
trainer.train(["What is Lycoris Radiata?",
               "A flower also called Spider Lily, which often represents death in Japanese culture",])
trainer.train(["Why did she get transferred?",
               "she started firing indiscriminately at the enemies in order to save a colleague that was taken as hostage, jeopardizing the safety of other Lycoris in the process",])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])

#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#characters
#ChisaTaki
trainer.train(["who is the main character?",
"Chisato Nishikigi and Takina Inoue.",])
trainer.train(["Who are the protagonists?",
               "Chisato Nishikigi, Takina Inoue",])

#Chisato
trainer.train(["who is Chisato Nishikigi?",
"The srongest Lycoris, known for her involvement in the destruction of the old radio tower",])
trainer.train(["What is the special skill of Chisato?",
    "She can dodge bullets.",])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])

#Takina
trainer.train(["Who is Takina Inoue?",
"A Lycoris who got transferred to work in LycoReco, where Chisato also works",])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])


trainer.train(["Who are the members of LycoReco?", "Mika, Mizuki, Chisato, Takina, Kurumi",])

#Mika
trainer.train(["Who is Mika?",
    "A black, former-trainer of Lycoris, current master of LycoReco cafe. His combat skills are better than Chisato's.",])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])

#Kurumi
trainer.train(["Who is Kurumi?",
    "A loli hacker who also has a name of 'Walnut'. Hacked into DA's AI 'Radiata'",])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])

#Mizuki
trainer.train([ "Who is Mizuki?",
    "Mizuki Nakahara, a former-Lycoris who has strong desire to date and marry with men",])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])


#Fuki
trainer.train(["Who is Fuki Harukawa?",
    "First-Lycoris who is close to Chisato, former-partner of Takina. Likes Mika",])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])

#Sakura
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])

#Erika, other Lycoris, Kusunoki, and others in DA
trainer.train(["Who is Sakura Otome?",
               "Second-Lycoris, replacement of Takina in Fuki's team",])
trainer.train(["Who is Kusunoki?",
               "The commander of DA",])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])

#customers of LycoReco
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])

#Silent Jin
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])

trainer.train(["Who are the villans?",
               "Majima, Robota, Shinji",])
trainer.train(["Who are the antagonists?",
               "Majima, Robota, Shinji",])
#Majima
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])

#Robota
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])

#Shinji the mf
trainer.train(["Who is Shinji?", "Shinji Yoshimatsu. A member of the Alan Institute. He sees Chisato as a weapon for killing",])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])

#other people
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])

#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#other things about lycoris recoil, like novel, manga, or producers, god-tier animaters, and people involving in making.
trainer.train(["What is Lycoris Recoil?", "It is an original Japanese anime TV series.",])
trainer.train(["What is it about?",
    "It is about two girls who works for a secret organization called DA(Direct Attack) ",])
trainer.train(["what is the ED?",
    "The ending theme of Lycoris Recoil is 'Tower of Flower'",])
trainer.train(["What is the OP?",
    "The OP of Lycoris Recoil is 'ALIVE' by ClaRis",])
trainer.train(["Lyrics of Tower of Flower please",
    "https://www.uta-net.com/song/321038/",])
trainer.train(["Lyrics of ALIVE please", "https://www.uta-net.com/song/321583/",])
trainer.train(["What is the title of episode 1?", "Easy does it",])
trainer.train(["What is the title of episode 2?","The more the merrier",])
trainer.train(["What is the title of episode 3?","More haste, less speed",])
trainer.train(["What is the title of episode 4?","Nothing seek, nothing found",])
trainer.train(["What is the title of episode 5?","So far, so good",])
trainer.train(["What is the title of episode 6?","Opposites attract",])
trainer.train(["What is the tilte of episode 7?","Time will tell",])
trainer.train(["What is the title of episode 8?","Another day, another dollar",])
trainer.train(["What is the title of episode 9?","What's done is done",])
trainer.train(["What is the title of episode 10","Repay evil with evil",])
trainer.train(["What is the title of episode 11","Diamond cut diamond",])
trainer.train(["What is the title of episode 12","Nature versus nurture",])
trainer.train(["What is the title of episode 13?", "Recoil of Lycoris",])
trainer.train(["What is the official website of Lycoris Recoil?", "https://lycoris-recoil.com/", ])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
#/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#others, anything else
trainer.train(["How are you?",
  "If you are seeing this message, I am correctly running.",])
trainer.train(["Hi",
  "Welcome, ask any question about Lycoris Recoil.",])
trainer.train(["Who are you?",
  "I am Radiata_B, I am an AI that was specialized for stuffs about Lycoris Recoil.",])
trainer.train(["Hello",
               "Welcome, ask any question about Lycoris Recoil."])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])
trainer.train([""])

os.system('cls')

exit_conditions = (":q", "quit", "exit")
cleanTheScreen = ("clean")
print("enter 'clean' to clean the screen")
print("enter 'quit' to stop")

while True:
    query = input("You: ")
    if query in exit_conditions:
        break
    elif query in cleanTheScreen:
        os.system('cls')
    else:
        print(f"Radiata_B:  {chatbot.get_response(query)}")